# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('hula-routing', ['core'])
    module.source = [
        'model/hula-routing.cc',
        'model/hula-tag.cc',
        'model/hula-probing.cc',
        'helper/hula-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('hula-routing')
    module_test.source = [
        'test/hula-routing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'hula-routing'
    headers.source = [
        'model/hula-routing.h',
        'model/hula-tag.cc',
        'model/hula-probing.h',
        'helper/hula-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

