## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('Dctcp-example',
                                 ['point-to-point', 'internet', 'applications', 'flow-monitor'])

    obj.source = 'Dctcp-example.cc'
    
